### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Linzm99** [ip-tools/python-epo-ops-client#103]
Hi I want to do a basic published data search request.

On my home PC it's working fine, but on my Laptop I get the

`requests.exceptions.SSLError: HTTPSConnectionPool(host='ops.epo.org', port=443): Max retries exceeded with url: /3.2/auth/accesstoken (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))`

error.

Code:
```
import epo_ops

client = epo_ops.Client(key='...', secret='...')  # Instantiate client
response = client.published_data_search('ti all "plastic"',1,25)
```

Is this a device configuration problem or some other library version problem?

Any ideas?

**Comment by dbolser** [comment]
Good question... Can you try comparing `pip freeze` on both PC and laptop? If I had to guess, I'd think that you have an old ssl version on your lappy... What OS on each? What version of Python?

**Comment by Linzm99** [comment]
This resolved by itself I tried it again and now it works. Thanks anyways!
