### ISSUE TITLE
Future maintenance of repository and package

### ISSUE THREAD

**Issue by amotl** [ip-tools/python-epo-ops-client#60]
Dear George,

first of all, I would like to thank you tremendously for conceiving and maintaining this package. I think it has a high value for open data and open access applications aiming to connect to EPO's OPS service to gather information.

At https://github.com/gsong/python-epo-ops-client/issues/59#issuecomment-1596298640, you mentioned that you are not actively working on this project anymore, and that you would welcome anyone to take it over.

In this spirit, I am offering my support. A few references about our past work in this area are attached below. Let me know if this resonates with you. 🌻 

With kind regards,
Andreas.

#### References

- https://github.com/marians/dwd-weather/issues/3
- https://github.com/xmpppy/xmpppy/issues/39
- https://github.com/m0nhawk/grafana_api/issues/88
- https://github.com/mqtt-tools/mqttwarn/issues/389#issuecomment-1537458116
- https://github.com/wireviz/WireViz/issues/316

**Comment by gsong** [comment]
@amotl Would completely trust you to take over this project. Do you want me to transfer it? I suppose we'd have to arrange for the PyPI transfer as well.

**Comment by amotl** [comment]
Dear George,

thanks for your trust, I appreciate it.

> Do you want me to transfer it? I suppose we'd have to arrange for the PyPI transfer as well.

I think it will be the best option to transfer to an organization, in order to bring in more maintainers. If you don't have any objections, I would like you to be part of it - just in case I am not around and we are not able to level up on co-maintainers.

So, I've just invited you as a member to the https://github.com/ip-tools organization, feel free to transfer the repository after accepting the invitation. On PyPI, I am also `amotl`, so you can easily add me as additional member over there. No transfer will be needed, because the package is not associated with a personal scope of any kind.

Thank you so far, and with kind regards,
Andreas.

**Comment by gsong** [comment]
Transfer on GitHub completed. PyPI collaborator invited.

**Comment by amotl** [comment]
Dear George,

thank you very much. After inviting you to the `ip-tools` organization as a member the other day, I just assigned you the `Admin` role on the `python-epo-ops-client` repository, so you still can run all actions on it, including administrative ones.

With kind regards,
Andreas.

**Comment by gsong** [comment]
> Unfortunately, the PyPI collaborator invitation expired, because I was on vacation at the time you submitted it. Maybe you can run it once more?

I've resent the invitation.

**Comment by amotl** [comment]
It worked well, and I've accepted the invitation. Thank you again.
