### ISSUE TITLE
Next steps in maintenance and modernization

### ISSUE THREAD

**Issue by amotl** [ip-tools/python-epo-ops-client#61]
Dear George,

thank you for your trust in handing over the maintenance of the repository on behalf of GH-60. In order to closer approach the project and code base, I would like to spend some iterations on submitting a few maintenance patches, both modernizing the sandbox infrastructure, and the CI configuration for this repository.

While doing it, I would like to gradually work towards a modern Python project setup, ultimately using Ruff as a main linter, a `pyproject.toml` file for describing project metadata, poethepoet as task runner, versioningit for versioning, and GitHub Actions (GHA) for CI purposes, as I am doing on all our other newly conceived projects as well (see, for example, [1,2]), so I can re-use many parts from there already without much effort.

Alongside the same iterations of modernizing the repository, I will also add support for Python 3.10 and 3.11 to the CI configuration. As I do not expect any changes, I believe the functional side of the code base will not be touched at all. Along the way, the `requirements`-based dependency management will be dissolved, and, if you agree, I will also dissolve the usage of `tox`. I don't know much about it, and I would like to get rid of the maintenance burden.

The modernization process will happen gradually, and the Make-based sandbox will still be around for a while, so you can get gradually accustomed with the modernization process. It is important for me that you do not have the feeling to get lost in this process, still I would like to make reasonably progress on that, because regular work will also re-start soon on my end.

In this spirit, I am humbly asking about any concerns or objections you may have about this topic, how much you would like to still be in the boat to be concerned with all the details, or whether you trust me enough to welcome all the small decisions I will make on those next steps, and/or if you are giving a general chèque en blanc on this.

I hope you are appreciating the plan outlined in this post in general, otherwise please let me know so I can back off correspondingly.

With kind regards,
Andreas.

[1] https://github.com/panodata/aika
[2] https://github.com/daq-tools/lorrystream

**Comment by gsong** [comment]
@amotl I trust you to make all the infrastructure changes, and any supporting code base changes to modernize the project.

Let me know if you have any questions on why I made certain choices (if I still remember them!)

I really appreciate the stewardship of this project. It seems to be used more than I originally expected.

**Comment by amotl** [comment]
Hi again,

other than the transition from `setup.py` to `project.toml`, I think most of the items enumerated above have been implemented already, so I think it will be safe to close this issue.

With kind regards,
Andreas.
