### ISSUE TITLE
Fix test case `test_mock_quota_exceeded`

### ISSUE THREAD

**Issue by amotl** [ip-tools/python-epo-ops-client#64]
## About

At https://github.com/ip-tools/python-epo-ops-client/pull/63#pullrequestreview-1594531498, we reported that the test case `test_mock_quota_exceeded` currently fails. The reason is:
```python
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://opsv31.docs.apiary.io//individual-per-hour-exceeded/publication/docdb/biblio
```

## References
- Maybe related: GH-65

**Comment by amotl** [comment]
Maybe the URL https://opsv31.docs.apiary.io/ is wrong?

```shell
export APIARY_URL=https://opsv31.docs.apiary.io/
```

**Comment by gsong** [comment]
@amotl I've sent you an email with the proper URL, but it's private so be treated as secret.

**Comment by amotl** [comment]
Thanks. I've just submitted GH-66, based on your suggestions.
