### ISSUE TITLE
Replace Apiary tests with monkeypatch or in-process mockery

### ISSUE THREAD

**Issue by amotl** [ip-tools/python-epo-ops-client#65]
Dear George,

in the [backlog](https://github.com/ip-tools/python-epo-ops-client/blob/main/docs/backlog.md) file, I've picked up that item which raised my interest.

> - Testing: Replace Apiary tests with monkeypatch? Or https://pypi.python.org/pypi/pytest-localserver.

Maybe you can quickly educate me what this Apiary API is used for?

- What does this API do?
- Is the test suite running against the Apiary API only? Why do I need an OPS account then?
- Where is the source code for the Apiary API, and how would one make changes to it?

Following up on that, I will be more than happy to help replacing that testing subsystem with something else more self-contained, if that makes sense and would actually be possible.

With kind regards,
Andreas.

**Comment by gsong** [comment]
* [Apiary end point definition](https://github.com/ip-tools/python-epo-ops-client/blob/main/apiary.apib)
* The test suite only uses Apiary for the error cases coming from OPS:
  * IndividualQuotaPerHour exceeded
  * RegisteredQuotaPerWeek exceeded

**Comment by amotl** [comment]
Dear George,

I see, now that makes sense. I already was wondering what the `apiary.apib` file was all about. If you think using an embedded mock server instead, like `pytest-localserver`, I will see what I can do on behalf of one of the next iterations.

With kind regards,
Andreas.

**Comment by gsong** [comment]
@amotl I'm not sure an embedded server is needed, or if you can just intercept http requests and inject mock responses without standing up a server. That's what I tend to do in the JavaScript world.

**Comment by amotl** [comment]
If that is enough, then the de facto standard package in this regard when it comes to mocking the `requests` library, is the [responses](https://pypi.org/project/responses/) library, and might be totally sufficient to serve the needs of the test suite.

**Comment by amotl** [comment]
Hi. GH-72 has a corresponding patch which uses the `responses` library for returning the corresponding error conditions.
