### ISSUE TITLE
Document Client interface

### ISSUE THREAD

**Issue by gsong** [ip-tools/python-epo-ops-client#7]
Document the `Client` interface more clearly in the README.

**Comment by amotl** [comment]
Dear George,

in the long run, it will be sweet if this project could gain a dedicated documentation on [Read the Docs](https://readthedocs.com), but that's a general thing. On this very issue, did you have any specific details on your mind?

With kind regards,
Andreas.

**Comment by gsong** [comment]
I think it's OK to close this until there's time to revisit docs.
