### ISSUE TITLE
Make sure PRs can be validated via Travis

### ISSUE THREAD

**Issue by gsong** [ip-tools/python-epo-ops-client#9]
Travis restricts PR access to secure environment variables. Let's make sure tests can be run using anonymous clients.

See https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests

**Comment by amotl** [comment]
After switching to GitHub Actions (GHA) with GH-63, you are now able to control the policy about this at the "Fork pull request workflows from outside collaborators" section on the [Actions permissions](https://github.com/ip-tools/python-epo-ops-client/settings/actions) settings page.

The default policy is to require approval for first-time contributors.
> _Only first-time contributors will require approval to run workflows._

---

![image](https://github.com/ip-tools/python-epo-ops-client/assets/453543/90319f13-c825-4cdc-8051-74d3ee6aa837)
